# services/advanced_mesh_generator.py
class AdvancedMeshGenerator:
    def generate_realistic_sword(self, components: List[Dict]) -> str:
        """Генерирует реалистичный меч с продвинутыми техниками"""
        code = [
            "import bpy",
            "import bmesh",
            "from mathutils import Vector, Matrix",
            "",
            "# ============================================================",
            "# РЕАЛИСТИЧНЫЙ МЕЧ - ПРОДВИНУТЫЕ ТЕХНИКИ",
            "# ============================================================",
            "",
            "# Очистка сцены",
            "bpy.ops.object.select_all(action='SELECT')",
            "bpy.ops.object.delete(use_global=False, confirm=False)",
            "",
            "# Создание меша через bmesh для большего контроля",
            "bm = bmesh.new()",
            "",
            "# Лезвие с плавными изгибами",
            "blade_verts = [",
            "    Vector((-0.05, 0, 0)), Vector((0.05, 0, 0)),",
            "    Vector((-0.08, 0, 0.5)), Vector((0.08, 0, 0.5)),", 
            "    Vector((-0.05, 0, 1.0)), Vector((0.05, 0, 1.0)),",
            "    Vector((-0.02, 0, 1.2)), Vector((0.02, 0, 1.2))",
            "]",
            "",
            "# Добавление вершин и создание faces",
            "for v in blade_verts:",
            "    bm.verts.new(v)",
            "bm.verts.ensure_lookup_table()",
            "",
            "# Создание плавного лезвия",
            "bm.faces.new([bm.verts[0], bm.verts[2], bm.verts[3], bm.verts[1]])",
            "bm.faces.new([bm.verts[2], bm.verts[4], bm.verts[5], bm.verts[3]])",
            "bm.faces.new([bm.verts[4], bm.verts[6], bm.verts[7], bm.verts[5]])",
            "",
            "# Создание меша и объекта",
            "blade_mesh = bpy.data.meshes.new('SharpBlade')",
            "bm.to_mesh(blade_mesh)",
            "bm.free()",
            "blade_obj = bpy.data.objects.new('SharpBlade', blade_mesh)",
            "bpy.context.collection.objects.link(blade_obj)",
            "",
            "# Модификаторы для реалистичности",
            "bevel = blade_obj.modifiers.new('Bevel', 'BEVEL')",
            "bevel.width = 0.002",
            "bevel.segments = 3",
            "",
            "subdiv = blade_obj.modifiers.new('Subdivision', 'SUBSURF')",
            "subdiv.levels = 2",
            "",
            "# Сглаживание",
            "bpy.ops.object.select_all(action='SELECT')",
            "bpy.ops.object.shade_smooth()",
            "",
            "print('✅ Реалистичный меч создан!')"
        ]
        
        return '\n'.join(code)
